# Generated by Django 3.0.1 on 2020-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
